# This file is populated AFTER terraform apply
# Replace the IP with the output from: terraform output server_public_ip

[webservers]
web01 ansible_host=YOUR_SERVER_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/devops-training-key.pem

[webservers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'