---
- name: Configure web servers
  hosts: role_webserver          # Matches dynamic inventory group
  become: yes
  gather_facts: yes

  vars_files:
    - "{{ playbook_dir }}/../group_vars/all/vars.yml"
    - "{{ playbook_dir }}/../group_vars/all/vault.yml"

  roles:
    - webserver